Enciclopedie/Controllers/CategoryController.cs
using Enciclopedie.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Enciclopedie.Controllers
{
    public class CategoryController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [AllowAnonymous]
        public ActionResult Index()
        {
            var categories = from category in db.Categories
                           orderby category.CategoryName
                           select category;
            ViewBag.Categories = categories;

            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
            }

            return View();
        }

        public ActionResult Show(int id)
        {
            Category category = db.Categories.Find(id);
            ViewBag.Category = category;

            ViewBag.afisareButoane = false;
            if (User.IsInRole("Administrator"))
            {
                ViewBag.afisareButoane = true;
            }

            return View(category);
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult New()
        {
            return View();
        }

        [Authorize(Roles = "Administrator")]
        [HttpPost]
        public ActionResult New(Category category)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Categories.Add(category);
                    db.SaveChanges();
                    TempData["message"] = "Categoria a fost adaugata!";
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(category);
                }
                
            }
            catch (Exception e)
            {
                return View(category);
            }
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int id)
        {
            Category category = db.Categories.Find(id);
            return View(category);
        }

        [Authorize(Roles = "Administrator")]
        [HttpPut]
        public ActionResult Edit(int id, Category requestCategory)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Category category = db.Categories.Find(id);
                    if (TryUpdateModel(category))
                    {
                        category.CategoryName = requestCategory.CategoryName;
                        db.SaveChanges();
                        TempData["message"] = "Categoria a fost modificata!";
                    }
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(requestCategory);
                }
            }
            catch (Exception e)
            {
                return View(requestCategory);
            }
        }

        [Authorize(Roles = "Administrator")]
        [HttpDelete]
        public ActionResult Delete(int id)
        {
            var articles = from art in db.Articles.Where(i => i.CategoryId == id)
                           select art;

            if(articles!=null)
            {
                foreach (var article in articles)
                {
                    var imageId = article.Id;
                    Image image = db.Images.Find(imageId);
                    if (image != null)
                    {
                        db.Images.Remove(image);
                    }
                    db.Articles.Remove(article);
                }
            }

            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            TempData["message"] = "Categoria a fost stearsa!";
            return RedirectToAction("Index");
        }
    }
}

Enciclopedie/Controllers/ImageController.cs
using Enciclopedie.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Enciclopedie.Controllers
{
    public class ImageController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [AllowAnonymous]
        public ActionResult Index()
        {
            var images = db.Images.Include("Article");

            ViewBag.Images = images;

            ViewBag.afisareButoane = false;
            if (User.IsInRole("Editor") || User.IsInRole("Administrator"))
            {
                ViewBag.afisareButoane = true;
            }
            ViewBag.esteAdmin = User.IsInRole("Administrator");

            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
            }

            return View();
        }

        [Authorize(Roles = "User,Editor,Administrator")]
        public ActionResult Show(int id)
        {
            Image image = db.Images.Find(id);
            ViewBag.Image = image;
            ViewBag.Article = image.Article;

            ViewBag.afisareButoane = false;
            if (User.IsInRole("Editor") || User.IsInRole("Administrator"))
            {
                ViewBag.afisareButoane = true;
            }
            ViewBag.esteAdmin = User.IsInRole("Administrator");

            return View(image);
        }

        [Authorize(Roles = "Editor,Administrator")]
        public ActionResult New()
        {
            Image image = new Image();

            // preluam lista de articole din metoda GetAllArticles()
            image.Articles = GetAllArticles();

            return View(image);
        }

        [NonAction]
        public IEnumerable<SelectListItem> GetAllArticles()
        {
            var selectList = new List<SelectListItem>();
            var articles = from art in db.Articles.Where(i => i.Available == true)
                             select art;
       
            foreach (var article in articles)
            {
                selectList.Add(new SelectListItem
                {
                    Value = article.Id.ToString(),
                    Text = article.Title.ToString()
                });
            }
        
            return selectList;
        }

        [Authorize(Roles = "Editor,Administrator")]
        [HttpPost]
        public ActionResult New(Image image)
        {
            image.Articles = GetAllArticles();

            string fileName = Path.GetFileNameWithoutExtension(image.ImageFile.FileName);
            string extension = Path.GetExtension(image.ImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            image.ImagePath = "~/Images/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Images/"), fileName);
            image.ImageFile.SaveAs(fileName);
       
            try
            {
                if (ModelState.IsValid)
                {
                    Article article = db.Articles.Find(image.Id);
                    article.Available = false;
                    UpdateModel(article);

                    db.Images.Add(image);
                    db.SaveChanges();
                    TempData["message"] = "Imaginea a fost adaugata!";

                    return RedirectToAction("Index");
                }
                else
                {
                    return View(image);
                }
            }
            catch (Exception e)
            {
                return View(image);
            }
        }

        [Authorize(Roles = "Editor,Administrator")]
        public ActionResult Edit(int id)
        {
            Image image = db.Images.Find(id);
            return View(image);
        }

        [Authorize(Roles = "Editor,Administrator")]
        [HttpPut]
        public ActionResult Edit(int id, Image requestImage)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Image image = db.Images.Find(id);

                    string fileName = Path.GetFileNameWithoutExtension(requestImage.ImageFile.FileName);
                    string extension = Path.GetExtension(requestImage.ImageFile.FileName);
                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    requestImage.ImagePath = "~/Images/" + fileName;
                    fileName = Path.Combine(Server.MapPath("~/Images/"), fileName);
                    requestImage.ImageFile.SaveAs(fileName);

                    if (TryUpdateModel(image))
                    {
                        image.ImageTitle = requestImage.ImageTitle;
                        image.ImagePath = requestImage.ImagePath;
                        image.ImageFile = requestImage.ImageFile;
                        db.SaveChanges();
                        TempData["message"] = "Imaginea a fost modificata!";

                        return RedirectToAction("Index");
                    }
                    return View(requestImage);
                }
                else
                {
                    return View(requestImage);
                }
            }
            catch (Exception e)
            {
                return View(requestImage);
            }
        }

        [Authorize(Roles = "Editor,Administrator")]
        [HttpDelete]
        public ActionResult Delete(int id)
        {
            Article article = db.Articles.Find(id);
            article.Available = true;
            UpdateModel(article);

            Image image = db.Images.Find(id);
            db.Images.Remove(image);
            db.SaveChanges();
            TempData["message"] = "Imaginea a fost stearsa!";
            return RedirectToAction("Index");
        }
    }
}

Enciclopedie/Controllers/UsersController.cs
using Enciclopedie.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Enciclopedie.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class UsersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {
            ViewBag.UsersList = db.Users
                .OrderBy(u => u.UserName)
                .ToList();

            return View();
        }

        public ActionResult Details(string id)
        {
            if (String.IsNullOrEmpty(id))
            {
                return HttpNotFound("Lipseste parametrul id!");
            }

            ApplicationUser user = db.Users
                .Include("Roles")
                .FirstOrDefault(u => u.Id.Equals(id));

            if (user != null)
            {
                ViewBag.UserRole = db.Roles
                    .Find(user.Roles.First().RoleId).Name;

                return View(user);
            }

            return HttpNotFound("Nu s-a gasit user-ul cu id-ul dat!");
        }

        public ActionResult Edit(string id)
        {
            if (String.IsNullOrEmpty(id))
            {
                return HttpNotFound("Lipseste parametrul id!");
            }
            UserViewModel uvm = new UserViewModel();
            uvm.User = db.Users.Find(id);
            IdentityRole userRole = db.Roles
                .Find(uvm.User.Roles.First().RoleId);
            
            uvm.RoleName = userRole.Name;
            
            return View(uvm);
        }

        [HttpPut]
        public ActionResult Edit(string id, UserViewModel uvm)
        {
            ApplicationUser user = db.Users.Find(id);

            try
            {
                if (TryUpdateModel(user))
                {
                    var um = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));

                    foreach (var r in db.Roles.ToList())
                    {
                        um.RemoveFromRole(user.Id, r.Name);
                    }

                    um.AddToRole(user.Id, uvm.RoleName);

                    db.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View(uvm);
            }
        }
    }
}

Enciclopedie/Views/Shared/ArticleInfo.cshtml
<div class="panel-heading">@Model.Title</div>
<div class="panel-body">
    Rezumat articol: <strong>@Model.Summary</strong>
    <br /><br /> <span class="label label-success">@Model.Date</span>
    <br /><br /> <i class="glyphicon glyphicon-globe">@Model.Category.CategoryName</i>
</div>
&nbsp &nbsp <i class="glyphicon glyphicon-user"></i> <i>articol scris de</i> <strong> @Model.User.UserName </strong>

Enciclopedie/Views/Shared/CategoryInfo.cshtml
<div class="panel-heading">@Model.CategoryName</div>

Enciclopedie/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Enciclopedie", "Index", "Article", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole("Administrator"))
                    {
                        <li>@Html.ActionLink("Galerie", "Index", "Image")</li>
                        <li>@Html.ActionLink("Afisare articole", "Index", "Article")</li>
                        <li>@Html.ActionLink("Afisare categorii", "Index", "Category")</li>
                        <li>@Html.ActionLink("Adauga articol", "New", "Article")</li>
                        <li>@Html.ActionLink("Adauga categorie", "New", "Category")</li>
                        <li>@Html.ActionLink("Afisare utilizatori", "Index", "Users")</li>
                    }
                    else if (User.IsInRole("Editor"))
                    {
                        <li>@Html.ActionLink("Galerie", "Index", "Image")</li>
                        <li>@Html.ActionLink("Afisare articole", "Index", "Article")</li>
                        <li>@Html.ActionLink("Afisare categorii", "Index", "Category")</li>
                        <li>@Html.ActionLink("Adauga articol", "New", "Article")</li>
                    }
                    else if (User.IsInRole("User"))
                    {
                        <li>@Html.ActionLink("Galerie", "Index", "Image")</li>
                        <li>@Html.ActionLink("Afisare articole", "Index", "Article")</li>
                        <li>@Html.ActionLink("Afisare categorii", "Index", "Category")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Galerie", "Index", "Image")</li>
                        <li>@Html.ActionLink("Afisare articole", "Index", "Article")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>